### ISSUE TITLE
Integers not saved in redis

### ISSUE THREAD

**Issue by zoomix** [benlund/roc#1]
When initiating an integer, no keys are created in redis. The same works for hashes and such. An example here. The expected outcome is to see integers increase with 5 each time the program is run. Same as the hash gets appended with each run.

```
require 'redis-roc'
require 'redis'

Store = ROC::Store::RedisStore.new(Redis.new)

integer = Store.init_integer("integer")
puts "Integer #{integer.value}"
integer = 0 if integer.value.nil?
integer += 5

stuff = Store.init_hash('stuff')
puts "stuff: #{stuff.to_h}"
stuff[rand(100).to_s] = 'something' 
```

**Comment by benlund** [comment]
ROC objects are wrapper objects around Redis data structures, so you can't assign directly to them and have the result appear in Redis. You must call the value= method.

To store the integer in Redis, do:

```
integer.value = integer + 5
```

You can, however, treat ROC objects like their Ruby equivalents for methods that read the value (like integer + 5 above).

**Comment by zoomix** [comment]
Baah. Of course. I don't know why I thought you'd overridden =. My bad.

Thanks for a very interesting project!
On Dec 20, 2011 9:13 PM, "benlund" <
reply@reply.github.com>
wrote:

**Comment by benlund** [comment]
Thank you!
